language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules


install:
  - npm install
script:
  - npm run test:coverage
  - npm run build
 
branches:
  only:
    - master
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token_rich
  local_dir: build
  on:
    branch: master